Update localizations
Sensotrend/sensotrend-uploader pull request #78
Opened 2022-03-10 21:22 UTC by mrinnetmaki

## Risk analysis

- [x] Risks of the implementation in this pull request have been analyzed with following results:
- No significant risks. 

## Significance

- [x] Analysis, is the software change considered significant (ref. [MDCG 2020-3, chart C](https://drive.google.com/file/d/1QAqBhV-6NzuqXCY20kH5cH0VTGl83Jj0/view?usp=sharing)), has been made with following result: 
- **Not significant change**, can be made to the product certified according MDD.
	- Reasons for the decision - Trivial text changes

## Security check-up

[https://github.com/OWASP/www-project-top-ten/blob/master/index.md](https://github.com/OWASP/www-project-top-ten/blob/master/index.md)
- [x] **1 Injection** - Trivial text changes
- [x] **2 Broken Authentication** - Trivial text changes
- [x] **3 Sensitive Data Exposure** - Trivial text changes
- [x] **4 XML External Entities (XXE)** - Trivial text changes
- [x] **5 Broken Access Control** - Trivial text changes
- [x] **6 Security Misconfiguration** - Trivial text changes
- [x] **7 Cross-Site Scripting XSS** - Trivial text changes
- [x] **8 Insecure Deserialization** - Trivial text changes
- [x] **9 Using Components with Known Vulnerabilities** - Trivial text changes
- [x] **10 Insufficient Logging & Monitoring** - Trivial text changes

2022-03-24 10:30 UTC, JaWetter approved these changes

2022-03-24 11:31 UTC, HannuHyttinen requested changes

2022-03-24 11:31 UTC, HannuHyttinen commented on app/constants/errorMessages.js
> +  E_MEDTRONIC_UNSUPPORTED: 'Tidepool Uploader does not support Minimed pumps 522, 722 or older, or the newer 6-series pumps. Sorry...',
En oikein ymmärtänyt, miksi "Sensotrend Uploader" on tässä ja muutamassa muussa virheviestissä muutettu muotoon "Tidepool Uploader". Onhan tämä tarkoituksellinen muutos?

2023-07-21 19:24 UTC, mrinnetmaki commented on app/constants/errorMessages.js
> +  E_MEDTRONIC_UNSUPPORTED: 'Tidepool Uploader does not support Minimed pumps 522, 722 or older, or the newer 6-series pumps. Sorry...',
On tarkoituksellinen muutos. Tuo merkkijono on tässä yhteydessä vain merkkijono ja se lokalisoidaan eri paikassa.

2023-07-21 19:24 UTC, merged