Localization update
Sensotrend/sensotrend-uploader pull request #79
Opened 2022-03-24 11:30 UTC by JaWetter

## Risk analysis

- [x] Risks of the implementation in this pull request have been analyzed with following results:
- No significant risks. 

## Significance
_Instruction: Remove bullet, which is not the analysis result._

- [x] Analysis, is the software change considered significant (ref. [MDCG 2020-3, chart C](https://drive.google.com/file/d/1QAqBhV-6NzuqXCY20kH5cH0VTGl83Jj0/view?usp=sharing)), has been made with following result: 
- **Not significant change**, can be made to the product certified according MDD.
	- Reasons for the decision - Only an update to localization

## Security check-up

[https://github.com/OWASP/www-project-top-ten/blob/master/index.md](https://github.com/OWASP/www-project-top-ten/blob/master/index.md)
- [x] **A01:2021-Broken Access Control** - Just a simple translation update, no changes made to user access.
- [x] **A02:2021-Cryptographic Failures** - No data is transmitted.
- [x] **A03:2021-Injection** - Just an update on localization, no access to database and users can't input data.
- [x] **A04:2021-Insecure Design** - No design needed, just translations.
- [x] **A05:2021-Security Misconfiguration** - No changes made to configurations
- [x] **A06:2021-Vulnerable and Outdated Components** - No components added or changed
- [x] **A07:2021-Identification and Authentication Failures** - No changes made to user identification and authentication
- [x] **A08:2021-Software and Data Integrity Failures** - no plugins, libraries or modules added.
- [x] **A09:2021-Security Logging and Monitoring Failures** - just an localization update, it has no access to any critical data.
- [x] **A10:2021-Server-Side Request Forgery** - just a localization update, no data is being fetched from remote resources.

2022-03-24 11:48 UTC, HannuHyttinen requested changes

2022-03-24 11:48 UTC, HannuHyttinen commented on locales/fi/translation.json
> +  "We found more than one device plugged in. Only plug in the device you intend to upload.": "Löysimme enemmän kuin yhden laitteen kytkettynä. Kytke vain yksi laite kun haluat lähettää tietoja.a",
...tietoja.a?

2022-03-24 11:48 UTC, HannuHyttinen commented on locales/fi/translation.json
> +  "Uploading Libre 2 data?": "Libre 2 tietojen lähetys?",
En keksi, missä tilanteessa tämä lause näytetään. Kysymysmerkki näyttää kuitenkin hassulta suomenkielisessä lauseessa, joka ei ole muodoltaan kysymys. En tiedä sitten, häiritsisikö silmää vähemmän, jos olisi "Lähetetäänkö Libre 2:n tietoja?".

2022-03-24 11:52 UTC, HannuHyttinen requested changes

2022-03-24 11:52 UTC, HannuHyttinen commented on locales/fi/translation.json
> +  "Choose File": "Valitse CSV",
Vähemmän tekniselle käyttäjälle voisi olla helpompi, jos olisi "Valitse tiedosto" ja "Valitse CSV-tiedosto".

2022-03-25 08:14 UTC, JaWetter commented on locales/fi/translation.json
> +  "Choose File": "Valitse CSV",
Tässä oli hieman ongelmia, aluksi kun laitoin "Valitse tiedosto" koska se on niin eri mittainen sana kuin englannin "Choose File" ei teksti oikein mennyt kunnolla tuossa painikkeessa. Laitoin "Valitse CSV" koska se on lyhyempi sana, mutta voin tätä vielä katsoa tarkemmin jos keksin jonkun keinon saada pidemmän tekstin näkymään paremmin painikkeessa.

2022-03-27 10:04 UTC, mrinnetmaki requested changes
Muutama kysymys. Ja minusta ei mitenkään kannattaisi laittaa englanninkielisiä käännöksiä noihin muunkielisiin käännöstiedostoihin.

2022-03-27 10:04 UTC, mrinnetmaki commented on locales/de/translation.json
> +  "Plug in PDA with micro-USB": "Plug in PDA with micro-USB",
Nämä kannattaisi varmaankin kääntää saksaksi? Jos ei, niin ennemmin jättää tyhjäksi. Muuten on jälkikäteen hankala löytää niitä kohtia, jotka ovat vielä oikeasti kääntämättä.

2022-03-27 10:04 UTC, mrinnetmaki commented on locales/en/translation.missing.json
> +  "Please set your LibreView date format to Year-Month-Day and export the CSV again": "Please set your LibreView date format to Year-Month-Day and export the CSV again",
Tämä tiedosto pitäisi päivittää. Kannattaa siis ensin tallentaa tyhjänä objektina tai poistaa kokonaan ja sitten käyttää tuota Uploaderia ja katsoa, mitä tähän tiedostoon kirjaantuu.

2022-03-27 10:04 UTC, mrinnetmaki commented on locales/es/translation.json
> +  "Plug in PDA with micro-USB": "Plug in PDA with micro-USB",
Sama kuin saksassa, ennemmin Google-käännettyinä tai pois jätettyinä. Ei englanniksi.

2022-03-27 10:04 UTC, mrinnetmaki commented on locales/fi/translation.json
> +  "Uploading Libre 2 data?": "Lähetetäänkö Libre 2:n tietoja?",
Tämän tarkoituksesta en ole ihan varma, mutta taitaa olla pikemminkin "Oletko lataamassa tietoja Libre 2 -vastaanottimesta?" tms. Eli kysymys, joka esitetään, jos joku on lataamassa Libre-tietoja, mutta lukijalaitteen ajuri ei osaakaan keskustella laitteen kanssa. Ja esittää sitten erilaisen virheviestin.

En siis ole varma, onko näin. Kannattaisi varmistaa. Tai jos on jo varmistettu, niin ookoo.

2022-03-27 10:04 UTC, mrinnetmaki commented on locales/fi/translation.json
> +  "Please set your LibreView date format to Year-Month-Day and export the CSV again": "Aseta LibreViewn päivämäärän muoto vuosi-kuukausi-päivä muotoon ja vie CSV uudestaan",
Aika monta muotoa tuossa. :)

Olisiko jotenkin noin:
"Aseta LibreView:n asetuksissa päivämäärä muotoon vuosi-kuukausi-päivämäärä ja lataa CSV-tiedosto uudelleen."

2022-03-27 10:04 UTC, mrinnetmaki commented on locales/fi/translation.json
> +  "Select CSV file downloaded from LibreView": "Valitse LibreView:sta ladattu CSV tiedosto",
CSV-tiedosto

2022-03-27 10:04 UTC, mrinnetmaki commented on locales/fr/translation.json
> +  "Plug in PDA with micro-USB": "Plug in PDA with micro-USB",
Sama kuin saksassa, ennemmin Google-käännettyinä tai pois jätettyinä. Ei englanniksi.

2022-03-27 10:04 UTC, mrinnetmaki commented on locales/it/translation.json
> +  "Plug in PDA with micro-USB": "Plug in PDA with micro-USB",
Sama kuin saksassa, ennemmin Google-käännettyinä tai pois jätettyinä. Ei englanniksi.

2022-03-27 10:04 UTC, mrinnetmaki commented on locales/no/translation.json
> +  "Plug in PDA with micro-USB": "Plug in PDA with micro-USB",
Sama kuin saksassa, ennemmin Google-käännettyinä tai pois jätettyinä. Ei englanniksi.

2022-03-27 10:04 UTC, mrinnetmaki commented on locales/sv/translation.json
> +  "Plug in PDA with micro-USB": "Plug in PDA with micro-USB",
Sama kuin saksassa, ennemmin Google-käännettyinä tai pois jätettyinä. Ei englanniksi.

2022-03-27 10:04 UTC, mrinnetmaki commented on package.json
> +  "version": "2.44.1",
Uploaderin versiovumero täytyy aina päivittää kahteen tiedostoon. Sekä tänne package.json-tiedostoon että app/package.json-tiedostoon.

2022-03-27 10:04 UTC, mrinnetmaki commented on styles/components/Upload.module.less
> +  width: 150px;
Mistä tämä muutos aiheutuu?

Ja onko nimenomaan `width` vai olisiko `min-width` parempi?

2022-04-01 08:01 UTC, HannuHyttinen approved these changes

2022-04-10 20:20 UTC, mrinnetmaki approved these changes
👍

2023-07-23 09:20 UTC, merged